# Preprocessing twitter-corpus-data that is used to validate the models

importing all necessary libraries

In [66]:
import pandas as pd # for data processing

setting to show full text content

In [67]:
pd.set_option('display.max_colwidth', None)

In [68]:
df = pd.read_csv('full-corpus.csv', header=None)

In [69]:
df

,0,1,2,3,4
0,Topic,Sentiment,TweetId,TweetDate,TweetText
1,apple,positive,126415614616154112,Tue Oct 18 21:53:25 +0000 2011,Now all @Apple has to do is get swype on the iphone and it will be crack. Iphone that is
2,apple,positive,126404574230740992,Tue Oct 18 21:09:33 +0000 2011,@Apple will be adding more carrier support to the iPhone 4S (just announced)
3,apple,positive,126402758403305474,Tue Oct 18 21:02:20 +0000 2011,Hilarious @youtube video - guy does a duet with @apple 's Siri. Pretty much sums up the love affair! http://t.co/8ExbnQjY
4,apple,positive,126397179614068736,Tue Oct 18 20:40:10 +0000 2011,@RIM you made it too easy for me to switch to @Apple iPhone. See ya!
...,...,...,...,...,...
5109,twitter,irrelevant,126855687060987904,Thu Oct 20 03:02:07 +0000 2011,me re copè con #twitter
5110,twitter,irrelevant,126855171702661120,Thu Oct 20 03:00:04 +0000 2011,Buenas noches genteeee :) #twitter los quierooo ...
5111,twitter,irrelevant,126854999442587648,Thu Oct 20 02:59:23 +0000 2011,#twitter tiene la mala costumbre de ponerce bno cuano yo me voy :/
5112,twitter,irrelevant,126854818101858304,Thu Oct 20 02:58:40 +0000 2011,"Oi @flaviasansi. Muito bem vinda ao meu #Twitter. Sempre dou followback pelo meu perfil profissional. Permaneça por aqui, certo? Abrass!"
5113,twitter,irrelevant,126854423317188608,Thu Oct 20 02:57:06 +0000 2011,"Eles arrastaram os barcos para a praia, deixaram tudo e #seguiram Jesus.(Lucas 5-11)e este foii o primeiro #twitter da historia humana #RT"

dropping unnecessary columns, only keeping 1 (as label) and 4 (as feature)

In [70]:
df = df.drop([0, 2, 3], axis =1)

In [71]:
df

,1,4
0,Sentiment,TweetText
1,positive,Now all @Apple has to do is get swype on the iphone and it will be crack. Iphone that is
2,positive,@Apple will be adding more carrier support to the iPhone 4S (just announced)
3,positive,Hilarious @youtube video - guy does a duet with @apple 's Siri. Pretty much sums up the love affair! http://t.co/8ExbnQjY
4,positive,@RIM you made it too easy for me to switch to @Apple iPhone. See ya!
...,...,...
5109,irrelevant,me re copè con #twitter
5110,irrelevant,Buenas noches genteeee :) #twitter los quierooo ...
5111,irrelevant,#twitter tiene la mala costumbre de ponerce bno cuano yo me voy :/
5112,irrelevant,"Oi @flaviasansi. Muito bem vinda ao meu #Twitter. Sempre dou followback pelo meu perfil profissional. Permaneça por aqui, certo? Abrass!"
5113,irrelevant,"Eles arrastaram os barcos para a praia, deixaram tudo e #seguiram Jesus.(Lucas 5-11)e este foii o primeiro #twitter da historia humana #RT"

In [72]:
new_header = ['Ground_Truth_Label', 'Text']
df.columns = new_header

only keeping positive and negative, dropping irrelevant and neutral

In [73]:
df_filtered = df.loc[df['Ground_Truth_Label'].isin(['positive', 'negative'])]

In [74]:
df_filtered

,target,Text
1,positive,Now all @Apple has to do is get swype on the iphone and it will be crack. Iphone that is
2,positive,@Apple will be adding more carrier support to the iPhone 4S (just announced)
3,positive,Hilarious @youtube video - guy does a duet with @apple 's Siri. Pretty much sums up the love affair! http://t.co/8ExbnQjY
4,positive,@RIM you made it too easy for me to switch to @Apple iPhone. See ya!
5,positive,I just realized that the reason I got into twitter was ios5 thanks @apple
...,...,...
3948,negative,#stupid fucking #Twitter #Twitterapp give me my Damn #mentions NOOWWWWWW!!!!! UGH! #DRAWLIN AS ALWAYS #TMW #PROMOALLDAY #FOLLOWLIMITISGAY TO
3949,negative,RT @JolieeSharmeda #twitter be fucking up
3950,negative,"@KushKitty420 you, #Facebook #twitter and the #tv are all #distractions whenever I wanna study ;("
3951,negative,"RT @VanillaLatte_xD: #omfg .. #Twitter , Why fxck up ? I wanna see my Retweets ""/"
3952,negative,"RT @nicolebanyots: #twitter UH, SHOW ME MY RETWEETS, OR ILL GO BACK TO FACEBOOK. K? K."

downsampling classes to equal size

In [75]:
value_counts = df_filtered['Ground_Truth_Label'].value_counts()
print(value_counts)

target
negative    572
positive    519
Name: count, dtype: int64

In [76]:
minority_class = value_counts.idxmin()
majority_class = value_counts.idxmax()

In [77]:
minority_count = value_counts.min()
print(minority_count)

519

In [78]:
df_majority = df[df['Ground_Truth_Label'] == majority_class]
df_minority = df[df['Ground_Truth_Label'] == minority_class]

In [79]:
df_majority

,target,Text
165,negative,RT @cjwallace03: So apparently @apple put MB cap on your SMS with the new update. 25mb storage before it tells you your inbox is full. W ...
166,negative,"RT @Jewelz2611 @mashable @apple, iphones r 2 expensive. Most went w/ htc/galaxy. No customer loyalty w/phone comp.."
167,negative,"@mashable @apple, iphones r 2 expensive. Most went w/ htc/galaxy. No customer loyalty w/phone comp.."
168,negative,THiS IS WHAT WiLL KiLL APPLE http://t.co/72Jw4z5c RiP @APPLE
169,negative,@apple why my tunes no go on my iPhone? iPhone lonely without them. silly #iOS5
...,...,...
3948,negative,#stupid fucking #Twitter #Twitterapp give me my Damn #mentions NOOWWWWWW!!!!! UGH! #DRAWLIN AS ALWAYS #TMW #PROMOALLDAY #FOLLOWLIMITISGAY TO
3949,negative,RT @JolieeSharmeda #twitter be fucking up
3950,negative,"@KushKitty420 you, #Facebook #twitter and the #tv are all #distractions whenever I wanna study ;("
3951,negative,"RT @VanillaLatte_xD: #omfg .. #Twitter , Why fxck up ? I wanna see my Retweets ""/"
3952,negative,"RT @nicolebanyots: #twitter UH, SHOW ME MY RETWEETS, OR ILL GO BACK TO FACEBOOK. K? K."

In [80]:
df_minority

,target,Text
1,positive,Now all @Apple has to do is get swype on the iphone and it will be crack. Iphone that is
2,positive,@Apple will be adding more carrier support to the iPhone 4S (just announced)
3,positive,Hilarious @youtube video - guy does a duet with @apple 's Siri. Pretty much sums up the love affair! http://t.co/8ExbnQjY
4,positive,@RIM you made it too easy for me to switch to @Apple iPhone. See ya!
5,positive,I just realized that the reason I got into twitter was ios5 thanks @apple
...,...,...
3881,positive,"#facebook, #Twitter , #spongebob, #nirvana. Great way to spend the night. :D"
3882,positive,RT @ahhfuckitsguss: #twitter can be so useful on letting out your feeling when you cant in the real world .
3883,positive,"My 3 biggest obsessions: #twitter, #dancemoms, and #desperatehousewives. &lt;3"
3884,positive,#twitter is jumpin as usual :)
3885,positive,My Facebook messed up and I had to make a new one so... add me! Haha at least #twitter is reliable

In [81]:
df_majority_downsampled = df_majority.sample(n=minority_count, random_state=42)

In [82]:
df_balanced = pd.concat([df_minority, df_majority_downsampled])

In [83]:
print("\nValue Counts after balancing:")
print(df_balanced['Ground_Truth_Label'].value_counts())

Value Counts after balancing:
target
positive    519
negative    519
Name: count, dtype: int64

adding target number to dataset

In [84]:
def map_target_to_label(target):
    if target == 'positive':
        return 4
    elif target == 'negative':
        return 0
    else:
        return None
df_balanced['target_number'] = df_balanced['Ground_Truth_Label'].apply(map_target_to_label)

In [85]:
df_balanced

,target,Text,target_number
1,positive,Now all @Apple has to do is get swype on the iphone and it will be crack. Iphone that is,4
2,positive,@Apple will be adding more carrier support to the iPhone 4S (just announced),4
3,positive,Hilarious @youtube video - guy does a duet with @apple 's Siri. Pretty much sums up the love affair! http://t.co/8ExbnQjY,4
4,positive,@RIM you made it too easy for me to switch to @Apple iPhone. See ya!,4
5,positive,I just realized that the reason I got into twitter was ios5 thanks @apple,4
...,...,...,...
2654,negative,@joannejacobs I'd like to criticise #Microsoft's Steve Ballmer face-to-face for all the pain & suffering their products cause. #justsaying,0
270,negative,@zombiebomber have been on the phone with @verizonwireless and @apple pretty much ever since then. Really annoyed.,0
2567,negative,"I gave a try to Windows 8 Dev. Preview and it was good but the UI is way too messy right now, waiting for the Beta #microsoft #windows8",0
166,negative,"RT @Jewelz2611 @mashable @apple, iphones r 2 expensive. Most went w/ htc/galaxy. No customer loyalty w/phone comp..",0
3913,negative,"@8Sunni Yeah shit happens, #Twitter is a real whore sometimes!",0

exporting dataset

In [86]:
df_balanced.to_csv('full_corpus_preprocessed.csv', index=False)